31 add new task bottom sheet android
Ultra-Techies/Todolist-android pull request #15
Opened 2022-03-03 17:14 UTC by Njumbi

Kindly review and merge

2022-03-04 06:54 UTC, malcolmmaima requested changes
Left some comments/suggestions ... But this looks really good 👏

2022-03-04 06:54 UTC, malcolmmaima commented on app/src/main/java/com/todoist_android/ui/home/BottomSheetFragment.kt
> +    }
```
binding.buttonAddTask.setOnClickListener {
            if (binding.editTextTaskName.text.isNullOrEmpty()) {
                Toast.makeText(requireContext(), "Task name cannot be empty", Toast.LENGTH_SHORT).show()
            } else {
                //get the task name, date and time
                val taskName = binding.editTextTaskName.text.toString()
                val taskDate = dateTime
                //create the task
                TodoTask(taskName, taskDate, taskStatus)
                //add the task to the database
                //dismiss the dialog
                dismiss()
            }
        }
```

2022-03-04 06:54 UTC, malcolmmaima commented on app/src/main/java/com/todoist_android/ui/home/BottomSheetFragment.kt
> +
```
private fun TodoTask(taskName: String, taskDate: String, taskStatus: String): Any {
//call API and pass the data
        return Toast.makeText(requireContext(), "Task name: $taskName, Date: $taskDate, Status: $taskStatus", Toast.LENGTH_SHORT).show()
    }
```

2022-03-04 06:54 UTC, malcolmmaima commented on app/src/main/java/com/todoist_android/ui/home/BottomSheetFragment.kt
> +
```
//default taskStatus is created
    private var taskStatus = "Created"
```

2022-03-05 17:42 UTC, Njumbi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add New Task (Bottom Sheet) - Android](https://trello.com/c/Phnyjy4v/31-add-new-task-bottom-sheet-android)

2022-03-07 12:31 UTC, malcolmmaima commented
Rebased to main

2022-03-07 13:44 UTC, malcolmmaima approved these changes

2022-03-07 13:45 UTC, merged